# Generated by Django 5.0.6 on 2024-09-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ON LINE', 'ON LINE'), ('OFF LINE', 'OFF LINE')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
