# Generated by Django 5.0.6 on 2024-09-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0004_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ON LINE', 'on line'), ('OFF LINE', 'off line')], default='OFF LINE', max_length=20),
        ),
    ]
