# Generated by Django 5.0.6 on 2024-09-24 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0006_comment_parent_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionsonpost',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='actions_on_post', to='socialmediaapp.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('like', 'Like'), ('comment', 'Comment'), ('dislike', 'Dislike'), ('follow', 'Follow')], max_length=20),
        ),
    ]
