# Generated by Django 5.0.6 on 2024-09-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0009_profile_friend_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='friend_requests', to='socialmediaapp.friendrequest'),
        ),
    ]
